
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE HTML>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@page import="java.util.ArrayList"%>

<html>
	<head>
	<meta charset="UTF-8"/>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<meta name="description" content=""/>
    <meta name="keywords" content=""/>
    <meta name="author" content="nookandcove">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="resources/images/ico/favicon.ico" type="image/x-icon" />
	<script type="text/javascript" src="resources/js/create_registry_validation.js"></script>
	<link rel="stylesheet" href="resources/css/registry_css/registry_signup.css" type="text/css">
			
	<script type="text/javascript">
 	$(document).ready(function() { 		
 	    var eventType1 = '<c:out value="${eventType}"/>'; var eventMonth1 = '<c:out value="${eventMonth}"/>'; var eventDay1 = '<c:out value="${eventDay}"/>'; var eventYear1 = '<c:out value="${eventYear}"/>'; var regUserName1 = '<c:out value="${regUserName}"/>'; var regFirstName1 = '<c:out value="${regFirstName}"/>'; var regLastName1 = '<c:out value="${regLastName}"/>'; var coRegFirstName1 = '<c:out value="${coRegFirstName}"/>'; var coRegLastName1 = '<c:out value="${coRegLastName}"/>'; var regAddress1 = '<c:out value="${regAddress}"/>'; var password1 = '<c:out value="${password}"/>'; var regSocialMedia1 = '<c:out value="${regSocialMedia}"/>'; var regVendorCouponId1 = '<c:out value="${regVendorCouponId}"/>';	    
 	    $("[name=eventType]").val(eventType1); $("[name=eventMonth]").val(eventMonth1); $("[name=eventDay]").val(eventDay1); $("[name=eventYear]").val(eventYear1); $("[name=regUserName]").val(regUserName1); $("[name=regFirstName]").val(regFirstName1); $("[name=regLastName]").val(regLastName1); $("[name=coRegFirstName]").val(coRegFirstName1); $("[name=coRegLastName]").val(coRegLastName1); $("[name=regAddress]").val(regAddress1); $("[name=password]").val(password1); $("[name=verifyPassword]").val(password1); $("[name=socialMediaReff]").val(regSocialMedia1); $("[name=vendorCouponCode]").val(regVendorCouponId1);
	    
        $('input[type="checkbox"]').click(function() { if($(this).prop("checked") == true){ $("#eventMonthId").val(null); $("#eventDayId").val(null); $("#eventYearId").val(null); $("#eventDateIdLabel").css("color","black"); } });
        var regErrorPage1 = '<c:out value="${regErrorPage}"/>'; var regAddrErrorPage1 = '<c:out value="${regAddrErrorPage}"/>'; var dateCheckOption1 = '<c:out value="${dateCheckOption}"/>';        
        if(dateCheckOption1 === "Date coming soon") { $('#dateCheckOptionId').prop('checked', true); }        
        if(regErrorPage1 === "This e-mail already exists!") { $("#page4DivDisplayRefId").show(); $("#page1DivDisplayRefId").hide(); }        
		if(regAddrErrorPage1 === "Please create your custom url!") { $("#page6DivDisplayRefId").show(); $("#page1DivDisplayRefId").hide(); }
 	}); 	
 	$(function () { var ddlYears = $("#eventYearId"); var currentYear = (new Date()).getFullYear(); for (var i = currentYear; i <= currentYear+50; i++) { var option = $("<option />"); option.html(i); option.val(i); ddlYears.append(option); } });
	function noOfdaysDisplay(month) { $('#eventDayId')[0].options.length = 0; var currentYearName = (new Date()).getFullYear(); var getDaysInMonth = new Date(currentYearName, $("#eventMonthId").val(), 0).getDate(); var noOfDaysDsp = $("#eventDayId"); noOfDaysDsp.append("<option value=''>--Day--</option>"); for (var i = 1; i <= getDaysInMonth; i++) { var option = $("<option />"); option.html(i); option.val(i); noOfDaysDsp.append(option); } }
    </script>
	</head>
	
		<body>		
		<div id="mainframe" class="section-content"> <div class="container">  
 		<div class="row top_adjustment_10"> <div class="col-md-1 col-sm-1"></div> 		
 		<div class="col-md-10 col-sm-10"> <div class="service-item"> <div class="service-description"> <div align="center"> <img src="resources/images/registry/create_a_registry/create_a_registry_image.jpg"/>						
		<div class="row top_adjustment_10"> <div class="col-md-2 col-sm-2"></div> <div class="col-md-8 col-sm-8">		
<!-- Page1 Display code -->		
		<div class="reg_signup_top_adj_frame" id="page1DivDisplayRefId">
		<div align="right"><font class="reg_red_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font></div>
		<div class="reg_signup_topd_frame_dsp"> <div class="top_adjustment_70"><img src="resources/images/registry/create_a_registry/reg_page1_cint_text_img.png"></div> <div class="reg_page1_small_text_dsp top_adjustment_40">A few quick questions to help you get set up...</div>					
		<div class="top_adjustment_40"><h4><button class="reg_page1_sub_button" id="page1NextPageDispRefId">Start</button></h4></div> </div> </div>
<!-- Page2 Display code -->		
		<div class="reg_signup_topdis_adj_frame" id="page2DivDisplayRefId">
		<div align="right"><font class="reg_black_dots_dsp">.</font> <font class="reg_red_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font></div>
		<div class="reg_signup_topd_frame_dsp"> <div class="reg_page2_heading_top_text_dsp top_adjustment_50"> <h3>Event Information</h3> </div> <div align="center" class="reg_signup_box_frame_wd"></div> <div class="reg_signup_main_frame_box"> <div class="reg_signup_main_frame_top_adj">
		<table><tbody> <tr><td class="reg_input_heading_text_dsp" id="eventTypeIdLabel">Event*: &nbsp;&nbsp;</td> <td><select id="eventTypeId" name="eventType" class="reg_page2_select_box"> <option value=''>Please Select Event </option>	<option value='Wedding'>Wedding</option> <option value='CommitmentCeremony'>Commitment Ceremony</option> <option value='Anniversary'>Anniversary</option> <option value='Housewarming'>Housewarming</option> <option value='Birthday'>Birthday</option> <option value='BridalShower'>Bridal Shower</option> <option value='BabyShower'>Baby Shower</option> <option value='Celebration'>Celebration</option></select></td></tr> </tbody></table>
		<table class="rsup_secdiv_toplf_adj"><tbody> <tr><td class="reg_input_heading_text_dsp" id="eventDateIdLabel">Event Date*: &nbsp;&nbsp;</td> <td><select id="eventMonthId" name="eventMonth" class="reg_page2_select_sub_box1"> <option value=''>Month</option> <option value='1'>January</option> <option value='2'>February</option> <option value='3'>March</option> <option value='4'>April</option> <option value='5'>May</option> <option value='6'>June</option> <option value='7'>July</option> <option value='8'>August</option> <option value='9'>September</option> <option value='10'>October</option> <option value='11'>November</option> <option value='12'>December</option> </select></td> <td><select id="eventDayId" name="eventDay" class="reg_page2_select_sub_box2"> <option value=''>Day</option> </select></td> <td><select id="eventYearId" name="eventYear" class="reg_page2_select_sub_box3"> <option value=''>Year</option> </select></td></tr> </tbody></table>					
		<table class="rsup_secdiv_lftop_cl"><tbody> <tr><td class="reg_input_heading_text_dsp"> &nbsp;&nbsp;</td> <td><input type="checkbox" name="dateCheckOption" id="dateCheckOptionId"> <font class="reg_page2_check_box_text_dsp">We haven't set a date yet</font></td></tr> </tbody></table> </div> </div>					
		<div class="rsup_main_div_height_cl"> <table class="rsup_main_div_width_cl">
		<tr><td align="left" class="rsup_main_div_cursor_cl"><font class="rsup_main_div_cursor_cl" id="page2PreviousPageDispRefId"><img src="resources/images/registry/create_a_registry/registry_back_image.jpg" title="PREVIOUS"/></font></td>
		<td align="right"><font class="reg_page2_next_butt_text_dsp" id="page2NextPageDispRefId">NEXT &nbsp;&nbsp;<img src="resources/images/registry/create_a_registry/registry_next_image.jpg" title="NEXT"/></font></td></tr> </table> </div> </div> </div>
<!-- Page3 Display code -->		
		<div class="reg_signup_topdis_adj_frame" id="page3DivDisplayRefId">
		<div align="right"><font class="reg_black_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font> <font class="reg_red_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font></div>
		<div class="reg_signup_topd_frame_dsp"> <div class="reg_page2_heading_top_text_dsp top_adjustment_50"> <h3>Contact Information</h3> </div> <div align="center" class="reg_signup_box_frame_wd"></div> <div class="reg_signup_main_frame_box"> <div class="reg_signup_main_frame_top_adj">
		<table><tbody> <tr><td class="reg_input_heading_text_dsp" align="right">Your Name*: &nbsp;&nbsp;</td> <td><input type="text" id="regFirstNameId" name="regFirstName" placeholder="First" maxLength="40" class="reg_page3_textfield_box" onkeyup = "checkFirstChar(event.keyCode, this);" onkeydown = "return checkFirstChar(event.keyCode, this);"></td> <td><input type="text" id="regLastNameId" name="regLastName" placeholder="Last" maxLength="30" class="reg_page3_textfield_box left_adjustment_30" onkeyup = "checkFirstChar(event.keyCode, this);" onkeydown = "return checkFirstChar(event.keyCode, this);"></td></tr> <tr class="rsup_three_div_height"><td></td><td></td><td></td></tr> <tr><td class="reg_input_heading_text_dsp" align="right">Co-Registrant's&nbsp;&nbsp;</td><td></td><td></td></tr> <tr><td class="reg_input_heading_text_dsp" align="right">Name: &nbsp;&nbsp;</td> <td><input type="text" id="coRegFirstNameId" name="coRegFirstName" placeholder="First" maxLength="40" class="reg_page3_textfield_box" onkeyup = "checkFirstChar(event.keyCode, this);" onkeydown = "return checkFirstChar(event.keyCode, this);"></td> <td><input type="text" id="coRegLastNameId" name="coRegLastName" placeholder="Last" maxLength="30" class="reg_page3_textfield_box left_adjustment_30" onkeyup = "checkFirstChar(event.keyCode, this);" onkeydown = "return checkFirstChar(event.keyCode, this);"></td></tr> </tbody></table> </div> </div>					
		<div class="rsup_main_div_height_cl"> <table class="rsup_main_div_width_cl"> <tr><td align="left" class="rsup_main_div_cursor_cl"><font class="rsup_main_div_cursor_cl" id="page3PreviousPageDispRefId"><img src="resources/images/registry/create_a_registry/registry_back_image.jpg" title="PREVIOUS"/></font></td> <td align="right"><font class="reg_page2_next_butt_text_dsp" id="page3NextPageDispRefId">NEXT &nbsp;&nbsp;<img src="resources/images/registry/create_a_registry/registry_next_image.jpg" title="NEXT"/></font></td></tr> </table> </div> </div> </div>
<!-- Page4 Display code -->		
		<div class="reg_signup_topdis_adj_frame" id="page4DivDisplayRefId">
		<div align="right"><font class="reg_black_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font> <font class="reg_red_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font></div>
		<div class="reg_signup_topd_frame_dsp"> <div class="reg_page2_heading_top_text_dsp top_adjustment_50"> <h3>Create Account</h3> </div> <div align="center" class="reg_signup_box_frame_wd"></div> <div class="reg_signup_main_frame_box"> <div class="reg_signup_main_frame_top_adj">
		<table><tbody> <c:if test="${not empty regErrorPage}"> <tr class="rsup_error_msg_top_dsp"><td></td> <td><img src="resources/images/warning.gif" class="rsup_error_msg_abs_cl"> <font class="rsup_error_msg_fonttxt_cl"> &nbsp;&nbsp;&nbsp;&nbsp; ${regErrorPage}</font></td></tr> </c:if> <tr><td class="reg_input_heading_text_dsp" align="right">Email*: &nbsp;&nbsp;</td> <td><input type="text" id="regEmailId" name="regUserName" class="reg_page4_textfield_box" onkeyup = "checkFirstChar(event.keyCode, this);" onkeydown = "return checkFirstChar(event.keyCode, this);"></td></tr> <tr class="rsup_all_div_height_cl"><td></td><td></td><td></td></tr> <tr><td class="reg_input_heading_text_dsp" align="right">Password*: &nbsp;&nbsp;</td> <td><input type="password" id="createPasswordId" name="password" class="reg_page4_textfield_box" onkeyup = "checkFirstChar(event.keyCode, this);" onkeydown = "return checkFirstChar(event.keyCode, this);"></td></tr> <tr class="rsup_all_div_height_cl"><td></td><td></td><td></td></tr>						
		<tr><td class="reg_input_heading_text_dsp" align="right">Verify Password*: &nbsp;&nbsp;</td> <td><input type="password" id="verifyPasswordId" name="verifyPassword" class="reg_page4_textfield_box" onkeyup = "checkFirstChar(event.keyCode, this);" onkeydown = "return checkFirstChar(event.keyCode, this);"></td></tr> </tbody></table> </div> </div>					
		<div class="rsup_main_div_height_cl"> <table class="rsup_main_div_width_cl"> <tr><td align="left" class="rsup_main_div_cursor_cl"><font class="rsup_main_div_cursor_cl" id="page4PreviousPageDispRefId"><img src="resources/images/registry/create_a_registry/registry_back_image.jpg" title="PREVIOUS"/></font></td> <td align="right"><font class="reg_page2_next_butt_text_dsp" id="page4NextPageDispRefId">NEXT &nbsp;&nbsp;<img src="resources/images/registry/create_a_registry/registry_next_image.jpg" title="NEXT"/></font></td></tr> </table> </div> </div> </div>
<!-- Page5 Display code -->		
		<div class="reg_signup_topdis_adj_frame" id="page5DivDisplayRefId">
		<div align="right"><font class="reg_black_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font> <font class="reg_red_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font></div>
		<div class="reg_signup_topd_frame_dsp"> <div class="reg_page2_heading_top_text_dsp top_adjustment_50"> <h3>Create Account</h3> </div> <div align="center" class="reg_signup_box_frame_wd"></div> <div class="reg_signup_main_frame_box"> <div class="reg_signup_main_frame_top_adj">
		<table class="top_adjustment_30"><tbody> <tr><td class="reg_input_heading_text_dsp" align="right">Where did you hear about us? &nbsp;&nbsp;</td> <td><select id="socialMediaReffId" name="socialMediaReff" class="reg_page5_sm_select_box"> <option value=''>---- Please Select ---- </option>	<option value='Facebook'>Facebook</option> <option value='Instagram'>Instagram</option> <option value='Pinterest'>Pinterest</option> <option value='Twitter'>Twitter</option> <option value='Google Search'>Google Search</option> <option value='Blog'>Blog</option> <option value='Wedding Vendor'>Wedding Vendor</option></select></td></tr> <tr class="rsup_all_div_height_cl"><td></td><td></td><td></td></tr>						
		<tr><td class="reg_input_heading_text_dsp" align="right">Please enter a referral code &nbsp;&nbsp;</td></tr> <tr><td class="reg_input_heading_text_dsp" align="right">if you have one: &nbsp;&nbsp;</td> <td><input type="text" id="vendorCouponCodeId" name="vendorCouponCode" maxLength="60" class="reg_vender_id_text_field_dsp"></td></tr> <tr class="rsup_all_div_height_cl"><td></td><td></td><td></td></tr> </tbody></table> </div> </div>					
		<div class="rsup_main_div_height_cl"> <table class="rsup_main_div_width_cl"> <tr><td align="left" class="rsup_main_div_cursor_cl"><font class="rsup_main_div_cursor_cl" id="page5PreviousPageDispRefId"><img src="resources/images/registry/create_a_registry/registry_back_image.jpg" title="PREVIOUS"/></font></td> <td align="right"><font class="reg_page2_next_butt_text_dsp" id="page5NextPageDispRefId">NEXT &nbsp;&nbsp;<img src="resources/images/registry/create_a_registry/registry_next_image.jpg" title="NEXT"/></font></td></tr> </table> </div> </div> </div>			
<!-- Page6 Display code -->		
		<div class="reg_signup_topdis_adj_frame" id="page6DivDisplayRefId">			
		<div align="right"><font class="reg_black_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font> <font class="reg_black_dots_dsp">.</font> <font class="reg_red_dots_dsp">.</font></div>
		<div class="reg_signup_topd_frame_dsp"> <div class="reg_page2_heading_top_text_dsp top_adjustment_50"> <h3>Your Registry Page</h3> </div> <div align="center" class="reg_signup_box_frame_wd"></div> <div class="reg_signup_main_frame_box"> <div class="reg_signup_main_frame_top_adj"> <div class="reg_page5_subheading_text_dsp"><h3>What do you want your address to be? </h3></div>
		<table class="top_adjustment_25"><tbody> <c:if test="${not empty regAddrErrorPage}"> <tr class="rsup_error_msg_ttop_cl"><td align="right"><img src="resources/images/warning.gif" class="rsup_error_msg_abs_cl"> <font class="rsup_error_msg_fonttxt_cl"> &nbsp;&nbsp;&nbsp;&nbsp; ${regAddrErrorPage}</font></td></tr></c:if> <tr><td class="reg_page5_ulr_text_dsp">https://www.nookandcove.com/registry/<input type="text" id="yourAddressId" name="regAddress" class="reg_page5_text_field_box"></td></tr> </tbody></table>
		<table class="rsup_chbox_text_dsp_cl" ><tbody> <tr><td><input type="checkbox" class="rsup_box_shw_height_cl" id="checkBoxReffNameId" name="checkBoxReffName" value=""/></td> <td><p>&nbsp;&nbsp;I accept the <a target="_blank" href="shopTermsPopupDisplay" class="rsup_cbox_tdcc_cl" onmouseover="this.style.color='red';" onmouseout="this.style.color='black';">Terms</a> and <a target="_blank" href="shopPrivacyPolicyPopup" class="rsup_cbox_tdcc_cl" onmouseover="this.style.color='red';" onmouseout="this.style.color='black'">Privacy Policy</a></p></td></tr> </tbody></table>					
		<form action="registryDataSaving" method="post" name="registryName">
		<div class="top_adjustment_45"><h4><button class="reg_page1_sub_button" id="letsDoThisReffId">Let's Do This!</button></h4></div>					
		<input type="hidden" name="eventType" id="regEventTypeId"> <input type="hidden" name="eventMonth" id="regEventMonthId"> <input type="hidden" name="eventDay" id="regEventDayId"> <input type="hidden" name="eventYear" id="regEventYearId"> <input type="hidden" name="dateCheckOption" id="regDateCheckOptionId"> <input type="hidden" name="regUserName" id="regiEmailId"> <input type="hidden" name="regFirstName" id="regiFirstNameId"> <input type="hidden" name="regLastName" id="regiLastNameId"> <input type="hidden" name="coRegFirstName" id="coRegiFirstNameId"> <input type="hidden" name="coRegLastName" id="coRegiLastNameId"> <input type="hidden" name="password" id="regCreatePasswordId"> <input type="hidden" name="regAddress" id="regYourAddressId"> <input type="hidden" name="regSocialMedia" id="regSocialMediaId"> <input type="hidden" name="regVendorCouponId" id="regVendorCouponCodeId">					
		</form> </div> </div>					
		<div class="rsup_main_div_height_cl"> <table class="rsup_main_div_width_cl"> <tr><td align="left" class="rsup_main_div_cursor_cl"><font class="rsup_main_div_cursor_cl" id="page6PreviousPageDispRefId"><img src="resources/images/registry/create_a_registry/registry_back_image.jpg" title="PREVIOUS"/></font></td> <td align="right"></td></tr> </table> </div> </div> </div>
<!-- Already Registry link code -->			
		<div align="center" class="top_adjustment_22"><font class="reg_alr_reg_text_dsp">Already registered?&nbsp; </font><a href="registryLogin" class="reg_signin_text_dsp">Sign In</a></div> </div>
		<div class="col-md-2 col-sm-2"></div> </div> </div> </div> </div> </div> <div class="col-md-1 col-sm-1"></div> </div> </div> </div>
		</body>
</html>