package com.nookandcove.service;

import java.sql.Timestamp;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.servlet.ModelAndView;
import org.json.simple.JSONArray;


public interface ClientInfoSavingService {
		
	public ModelAndView selectedSpace(HttpServletRequest req, HttpSession sn);
	public ModelAndView signUpRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView selectedStyle(HttpServletRequest req, HttpSession sn);
	public ModelAndView paymentInfoSavingInDB(HttpServletRequest req, HttpSession sn);
	public ModelAndView zeroPaymentInfoSavingInDB(HttpServletRequest req, HttpSession sn);
	public ModelAndView zeroPackageCheckoutPaymentDisplay(HttpServletRequest req, HttpSession sn, String amount, String totalAmount, String giftAmount, String promoCodePrice, String giftCuponCode, String remGiftCardPrice, double remGiftAmount);
	public ModelAndView paymentInfoSuccessRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView giftCardPayInPackgeRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView promoCodePayInPackgeRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView questionnerFullAndAccPackageEmailForClient(HttpServletRequest req, HttpSession sn);
	public ModelAndView questionnerFullAndAccPackageEmailForAdmin(HttpServletRequest req, HttpSession sn);
	public ModelAndView allocateBudget(HttpServletRequest req, HttpSession sn);
	public ModelAndView selectedDesignPackage(HttpServletRequest req, HttpSession sn);
	public ModelAndView roomDimensions(HttpServletRequest req, HttpSession sn);	
	public ModelAndView clientsInformationDisplayRedirection(HttpServletRequest req, HttpSession sn);	
	public ModelAndView clientInfoDisplaySavingRed(HttpServletRequest req, HttpSession sn);	
	public ModelAndView modifyClientsInformation(HttpServletRequest req, HttpSession sn, long clientInfoId);	
	public ModelAndView addNewClient(HttpServletRequest req, HttpSession sn);	
	public ModelAndView selStyleBackMove(HttpServletRequest req, HttpSession sn);
	public ModelAndView designPackBackMove(HttpServletRequest req, HttpSession sn);	
	public ModelAndView moreAboutSpaceUploadImagesInDB(MultipartFile file, HttpServletRequest req, HttpSession sn) throws Exception;
	public ModelAndView messageMyDesigners(HttpServletRequest req, HttpSession sn);	
	public ModelAndView startTheBusiness(HttpServletRequest req, HttpSession sn);	
	public JSONArray deleteImageFromDBUsingJSON(String deletedImage, HttpSession sn);	
	public ModelAndView reDirMoreAboutSpaceUpImgsInDB(HttpServletRequest req, HttpSession sn);	
	public JSONArray shareInspDeleteImageFromDBUsingJSON(String deletedImage, HttpSession sn);
	public ModelAndView clientMessageSendToDesignerRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView clientOneTimeSentMailToDesigner(HttpServletRequest req, HttpSession sn, long designInfoId);
	public ModelAndView clientAndDesignerMessageInfoRedirection(HttpServletRequest req, HttpSession sn);
	public JSONArray deleteSelectedProductFromCart(long productSavingId, HttpSession sn);	
	public JSONArray addSelectedProductsToCart(long productSavingId, int productCount, HttpSession sn);
	public ModelAndView selectedItemsDisplayInJSP(HttpServletRequest req, HttpSession sn, String refSpaceName);
	public String customerNameFromDB(long userId);	
	public int totalAddCartItemsCountFromDB(HttpSession sn);
	public String todayDateGettingFromCurrentDate();
	public String timeGettingFromCurrentDate();
	public Timestamp currentDate();
	public ModelAndView dimensionBackMove(HttpServletRequest req, HttpSession sn);
	public ModelAndView feelAboutColorRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView typeOfColorBackMove(HttpServletRequest req, HttpSession sn);
	public ModelAndView needSpaceItemsBackMove(HttpServletRequest req, HttpSession sn);
	public ModelAndView needSpaceItemsDataSavingInDB(HttpServletRequest req, HttpSession sn);
	public ModelAndView typeOfArtDataSavingInDB(HttpServletRequest req, HttpSession sn);
	public ModelAndView typeOfArtBackMove(HttpServletRequest req, HttpSession sn);
	public ModelAndView aboutSpaceImgBackMove(HttpServletRequest req, HttpSession sn);
	public ModelAndView aboutSpaceDataSavingInDB(HttpServletRequest req, HttpSession sn);
	public ModelAndView reDirShareInspirationUpImgsInDB(HttpServletRequest req, HttpSession sn);
	public ModelAndView shareInspirationUpImgInDB(MultipartFile fileUpload, HttpServletRequest req, HttpSession sn) throws Exception;
	public ModelAndView shareInspirationDataSavingInDB(HttpServletRequest req, HttpSession sn);
	public ModelAndView shareInspImgBackMove(HttpServletRequest req, HttpSession sn);
	public ModelAndView roomModificationRed(HttpServletRequest req, HttpSession sn);
	public ModelAndView roomManagement(HttpServletRequest req, HttpSession sn);
	public ModelAndView styleManagement(HttpServletRequest req, HttpSession sn);
	public ModelAndView styleModificationRed(HttpServletRequest req, HttpSession sn);
	public ModelAndView budgetManagement(HttpServletRequest req, HttpSession sn);
	public ModelAndView budgetModificationRed(HttpServletRequest req, HttpSession sn);
	public ModelAndView dimensionsManagement(HttpServletRequest req, HttpSession sn);
	public ModelAndView dimensionsModificationRed(HttpServletRequest req, HttpSession sn);
	public ModelAndView colorManagement(HttpServletRequest req, HttpSession sn);
	public ModelAndView colorModificationRed(HttpServletRequest req, HttpSession sn);
	public ModelAndView furnitureManagement(HttpServletRequest req, HttpSession sn);
	public ModelAndView furnitureModificationRed(HttpServletRequest req, HttpSession sn);
	public String itemsWallArtValueSearch(HttpServletRequest req, HttpSession sn, String typeOfItems);
	public ModelAndView artManagement(HttpServletRequest req, HttpSession sn);
	public ModelAndView artModificationRed(HttpServletRequest req, HttpSession sn);
	public ModelAndView myRoomManagement(HttpServletRequest req, HttpSession sn);
	public ModelAndView myRoomModificationRed(HttpServletRequest req, HttpSession sn);
	public ModelAndView modClMoreAboutSpaceUploadImagesInDB(MultipartFile fileUpload, HttpServletRequest req, HttpSession sn) throws Exception;
	public ModelAndView reDirModClMoreAboutSpaceUpImgsInDB(HttpServletRequest req, HttpSession sn);
	public ModelAndView inspirationManagement(HttpServletRequest req, HttpSession sn);
	public ModelAndView inspirationModificationRed(HttpServletRequest req, HttpSession sn);
	public ModelAndView modClShareInspirationUpImgInDB(MultipartFile shareInspImgUpload, HttpServletRequest req, HttpSession sn) throws Exception;
	public ModelAndView reDirModClShareInspirationUpImgsInDB(HttpServletRequest req, HttpSession sn);
	public ModelAndView styleModificationBackMove(HttpServletRequest req, HttpSession sn);	
	public ModelAndView shippingInformationDisplay(HttpServletRequest req, HttpSession sn);
	public ModelAndView billingInformationDisplay(HttpServletRequest req, HttpSession sn);
	public ModelAndView shippingAddressSavingOrUpdateInDB(HttpServletRequest req, HttpSession sn, String shipFullName, String shipAddress1, String shipAddress2, String shipCity, String shipState, String shipZip, String shipCountry, String shipPhNumber);
	public ModelAndView paymentReviewBackMoveRed(HttpServletRequest req, HttpSession sn);
	public ModelAndView billingInformationDataSavingInDB(HttpServletRequest req, HttpSession sn);
	public ModelAndView changeShippingInfoDisplay(HttpServletRequest req, HttpSession sn);
	public ModelAndView changeBillingInfoDisplay(HttpServletRequest req, HttpSession sn);	
	public ModelAndView accConceptsRedirection(HttpServletRequest req, HttpSession sn);
	public String conceptsLikeImagesDisplay(HttpServletRequest req, HttpSession sn, long clientInfoId, long designInfoId);
	public ModelAndView revisedConceptsRequestRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView accFinalConceptsRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView myRoomInformationRedirection(HttpServletRequest req, HttpSession sn);
	public JSONArray conceptsLikeUpdateInDB(String likeStatus, HttpSession sn);
	public ModelAndView accShopRedirRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView concept1ViewShopProductsRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView concept1ProductAddToCartRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView concept2ViewShopProductsRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView reDirConcept1ProductAddToCart(HttpServletRequest req, HttpSession sn);
	public ModelAndView concept2ProductAddToCartRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView reDirConcept2ProductAddToCart(HttpServletRequest req, HttpSession sn);
	public ModelAndView finalConceptViewShopProductsRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView finalConceptProductAddToCartRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView reDirFinalConceptProductAddToCart(HttpServletRequest req, HttpSession sn);
	public ModelAndView shopViewShopProductsRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView shopProductAddToCartRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView reDirShopFinalProductAddToCart(HttpServletRequest req, HttpSession sn);
	public ModelAndView paymentShoppingCartInfoDisplay(HttpServletRequest req, HttpSession sn);
	public ModelAndView reviewAndPlaceOrderDisplay(HttpServletRequest req, HttpSession sn);	
	public ModelAndView changeShippingInfoSavingInDB(HttpServletRequest req, HttpSession sn);
	public ModelAndView changeBillingInfoSavingInDB(HttpServletRequest req, HttpSession sn);	
	public ModelAndView fullRmConceptsRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRmRenderingChecking(HttpServletRequest req, HttpSession sn, String roomRenderingReq, String secRenPayStatus, String secRenderingReq);
	public JSONArray fullRoomConceptsLikeUpdateInDB(String likeStatus, HttpSession sn);
	public String fullRoomConceptsLikeImagesDisplay(HttpServletRequest req, HttpSession sn, long clientInfoId, long designInfoId);
	public ModelAndView renderingConsRequestRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView secRenderingConsRequestRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRmRenderingRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRmSingleRevisedRenderingRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRmDoubleRevisedRenderingRedirection(HttpServletRequest req, HttpSession sn);
	public String fullRoomDsnRevisedRendLikeImagesDisplay(HttpServletRequest req, HttpSession sn, long clientInfoId, long designInfoId);
	public JSONArray doubleRevisedRenderingLikeUpdateInDB(String likeStatus, HttpSession sn);
	public ModelAndView fullRmDoubleRevisedRenderingViewShopProductsRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRmSingleRevisedRenderingViewShopProductsRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRmRevisedDoubleRenderingProductAddToCartRedirection(HttpServletRequest req, HttpSession sn);
	public String fullRoomDsn2ndRendLikeImagesDisplay(HttpServletRequest req, HttpSession sn, long clientInfoId, long designInfoId);
	public ModelAndView fullRmDesnRoomRenderingRedOnly(HttpServletRequest req, HttpSession sn, long clientInfoId, long designInfoId);
	public ModelAndView fullRmSingleRenderingRedirection(HttpServletRequest req, HttpSession sn, long clientInfoId, long designInfoId);
	public ModelAndView fullRmDoubleRenderingRedirection(HttpServletRequest req, HttpSession sn, long clientInfoId, long designInfoId);
	public ModelAndView fullRmDesnRenderingReqRevisionRedirection(HttpServletRequest req, HttpSession sn);	
	public ModelAndView fullRmConcept1ViewShopProductsRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRmConcept2ViewShopProductsRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRmRenderingViewShopProductsRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView reDirFullRmConcept1ProductAddToCart(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRmConcept1ProductAddToCartRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView reDirFullRmConcept2ProductAddToCart(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRmConcept2ProductAddToCartRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView reDirFullRmRenderingProductAddToCart(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRmRenderingProductAddToCartRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView reDirFullRmRevisedDoubleRenderingProductAddToCart(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRmShopRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView reDirFullRm2ndSingleRenderingProductAddToCart(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRmShopViewShopProductsRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView reDirFullRm2ndDoubleRenderingProductAddToCart(HttpServletRequest req, HttpSession sn);
	public ModelAndView reDirFullRmShopProductAddToCart(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRmShopProductAddToCartRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRmSecRenderingRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView secRenderingConsPaymentRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView giftCardInfoChecInRenderingRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView giftCardPurchasedEmailSendToClient(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRmDoubleRenderingViewShopProductsRedirection(HttpServletRequest req, HttpSession sn);
	public JSONArray doubleRenderingLikeUpdateInDB(String likeStatus, HttpSession sn);
	public ModelAndView fullRmSecRenderingConceptsRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRmSingleSecondRenderingRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRmDoubleSecondRenderingRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView secondRenderingPaymentInfoSavingInDb(HttpServletRequest req, HttpSession sn);
	public ModelAndView zeroSecondRenderingPaymentInfoSavingInDb(HttpServletRequest req, HttpSession sn);
	public ModelAndView zeroSecRenderingCheckoutPaymentDisplay(HttpServletRequest req, HttpSession sn, String amount, String totalAmount, String giftAmount, String giftCuponCode, String remGiftCardPrice, double remGiftAmount);
	public JSONArray singleSecRendLikeUpdateInDB(String likeStatus, HttpSession sn);
	public JSONArray doubleSecRendLikeUpdateInDB(String likeStatus, HttpSession sn);
	public String fullRoomSecRendConceptsLikeImagesDisplay(HttpServletRequest req, HttpSession sn, long clientInfoId, long designInfoId);
	public String newImagesDisplayInManagement(HttpServletRequest req, HttpSession sn, long clientInfoId);
	public ModelAndView fullRmDouble2ndRenderingViewShopProductsRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRm2ndDoubleRenderingProductAddToCartRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRmSingle2ndRenderingViewShopProductsRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRm2ndSingleRenderingProductAddToCartRedirection(HttpServletRequest req, HttpSession sn);
	public JSONArray doubleRoomRenderingLikeUpdateInDB(String likeStatus, HttpSession sn);
	public String fullRoomDsnRoomRendLikeImagesDisplay(HttpServletRequest req, HttpSession sn, long clientInfoId, long designInfoId);
	public JSONArray finalConceptsLikeUpdateInDB(String likeStatus, HttpSession sn);	
	public ModelAndView fullRmDesnRoomRenderingInfoRedOnly(HttpServletRequest req, HttpSession sn, long clientInfoId, long designInfoId);
	public ModelAndView fullRmDesnRoomRenderingInfoDisplayRedOnly(HttpServletRequest req, HttpSession sn, long clientInfoId, long designInfoId);
	public ModelAndView fullRmSingleRenderingInfoDisplayRedirection(HttpServletRequest req, HttpSession sn, long clientInfoId, long designInfoId);
	public ModelAndView fullRmDoubleRenderingInfoDisplayRedirection(HttpServletRequest req, HttpSession sn, long clientInfoId, long designInfoId);	
	public ModelAndView fullRoomConcepViewShopProductsRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRoomRenderingViewShopProductsRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRoomReviseRenderingViewShopProductsRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView fullRoom2ndRenderingViewShopProductsRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView designerProfileInfoDisplayRed(HttpServletRequest req, HttpSession sn, long designerUserId);
	public ModelAndView justAboutFinishedQuestionnaireSavingInDB(HttpServletRequest req, HttpSession sn);
	public ModelAndView myDashBoardRedirection(HttpServletRequest req, HttpSession sn);	
	public ModelAndView clientRequestForConAndRendSentMailToDesigner(HttpServletRequest req, HttpSession sn, long designInfoId);
	public ModelAndView reviewPlaceOrderDataSavingInDB(HttpServletRequest req, HttpSession sn);
	public ModelAndView cartPaymentGiftCardInfoRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView clientMyAccountRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView clientAccountInfoUpdateInDB(HttpServletRequest req, HttpSession sn);
	public ModelAndView clientPasswordChangeRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView clientPasswordInfoUpdateInDB(HttpServletRequest req, HttpSession sn);
	public String giftCardCouponCodesCheckingInDB(String gcCopons, String payGiftCard);
	public double giftCardCouponPriceCheckingInDB(String gcCopons, String cartGftDBPrice);
	public ModelAndView cartPaymentPurchaseToGatewayRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView zeroCartPaymentPurchaseToGatewayRedirection(HttpServletRequest req, HttpSession sn);
	public ModelAndView zeroCatCheckoutPaymentDisplay(HttpServletRequest req, HttpSession sn, String giftCopons, long paymentInfoSavingId, String amount);
	public ModelAndView catCheckoutPaymentNoValueSelectionDisplay(HttpServletRequest req, HttpSession sn, String giftCopons, long paymentInfoSavingId, long cardNumber, String expirationDate, int cardCode, String apiLoginId, String transactionKey, String amount, String nameOnCard, String typeOfCard);
	public ModelAndView doNotPlaceShoppingCartSentMailToAdmin(HttpServletRequest req, HttpSession sn);
	public ModelAndView clientShoppingCartSentMailToAdmin(HttpServletRequest req, HttpSession sn);
	public ModelAndView cartGiftCardAmountUpdatesInDB(HttpServletRequest req, HttpSession sn, String giftCopons);
	public ModelAndView cartMultipleGiftCardsUpdateInDB(HttpServletRequest req, HttpSession sn, String giftCouponCOde);
	
}
