<!DOCTYPE html>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<html>    
    <head>        
    <meta charset="UTF-8"/>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<meta name="description" content=""/>
    <meta name="keywords" content=""/>
    <meta name="author" content="nookandcove">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="resources/css/registry_css/registry_static.css" type="text/css">
    <link rel="shortcut icon" href="resources/images/ico/favicon.ico" type="image/x-icon">    
    <script type="text/javascript">
    $(document).ready(function() {
    	var hashValue = location.hash.substr(1);
    	if(hashValue == "s1") { $('html, body').animate({scrollTop: $('#s1').offset().top}, 0); } else if(hashValue == "s2") { $('html, body').animate({scrollTop: $('#s2').offset().top}, 0); } else if(hashValue == "s3") { $('html, body').animate({scrollTop: $('#s3').offset().top}, 0); }    	
    });
    </script>        
	</head>	
		<body class="hrben_body_adj">		
			<div id="reg_how_it_works_frame" class="section-content"> <div class="container">       
			<div class="desktop"> <div class="row top_adjustment_50"> <div class="col-md-12 col-sm-12"> <div class="service-item"> <div class="service-description" align="center"> <table class="how_it_wks_mt_mb_dsp_cl"> <tbody> <tr> <td><div class="how_it_wks_bg_bord_dsp_cl"> <font class="big_font_flt_dsp">H</font><font class="big_font_rt_dsp">OW&nbsp;</font> <font class="big_font_flt_dsp">I</font><font class="big_font_rt_dsp">T&nbsp;</font> <font class="big_font_flt_dsp">W</font><font class="big_font_rt_dsp">ORKS</font> </div></td> <td><font class="midium_font_flt_dsp">&nbsp;&nbsp;&nbsp;3&nbsp;</font> <font class="midium_font_flt_dsp">W</font><font class="midium_font_rt_dsp">AYS&nbsp;</font> <font class="midium_font_rt_dsp">TO&nbsp;</font> <font class="midium_font_flt_dsp">A</font><font class="midium_font_rt_dsp">DD&nbsp;</font> <font class="midium_font_rt_dsp">TO&nbsp;</font> <font class="midium_font_flt_dsp">Y</font><font class="midium_font_rt_dsp">OUR&nbsp;</font> <font class="midium_font_flt_dsp">R</font><font class="midium_font_rt_dsp">EGISTRY&nbsp;</font> </td> </tr> </tbody> </table> </div> </div> </div> </div>	
			<div id="s1" class="how_it_wks_mt_adj_cl"> <div class="how_it_wks_pdnt_adj_cl"> <div class="step one"> <img src="resources/images/registry_learnmore/concept_boards_img.png"> <div class="black horizontal line mobile"></div> <div class="description"> <h1 class="title"><font class="heading_font_rt_dsp">C</font>URATED <font class="heading_font_rt_dsp">D</font>ESIGN <font class="heading_font_rt_dsp">B</font>OARDS</h1> <p>The Registry at Nook+Cove is unlike any another out there. Our designers keep up with the latest trends in a variety of design styles. They source from a highly vetted selection of top home decor retailers and brands. This allows them to curate beautiful design boards in a variety of styles with quality pieces for rooms throughout your home. </p> <p class="how_it_wks_top_adj_cl">You can browse our pre-curated design boards by room and add furniture and decor pieces to your registry. With our registry you don't have to worry about asking for non-traditional or more expensive gifts. Our group gifting feature allows you to easily convert any gift into a group gift. You also get to choose when your gift ships, giving you more control over your registry. </p> <p class="how_it_wks_top_adj_cl">So what do you really get when you register with Nook+Cove? A beautiful home with a designer look that is reflective of your style and needs - without the pay per hour designer price tag. Your guests will also be thrilled when they visit and see how their gifts and contributions have helped bring your home to life! </p> </div> </div> </div> </div>
			<div id="s2" class="how_it_wks_mt_adj_cl"> <div class="how_it_wks_pdnt_adj_cl"> <div class="step one"> <img src="resources/images/registry_learnmore/cash_funds_img.png"> <div class="black horizontal line mobile"></div> <div class="description"> <h1 class="title"><font class="heading_font_rt_dsp">C</font>ASH <font class="heading_font_rt_dsp">F</font>UNDS</h1> <p>Our Cash Funds feature allows you to customize funds for whatever your future holds! We've come up with a few options that you can choose from, such as a charity fund, honeymoon fund, down payment fund and others. Or you can create your own custom fund! </p> <p class="how_it_wks_top_adj_cl">Creating a custom fund is as easy as uploading a fun picture and naming the fund, such as: Ski Lessons for Two - the options are endless! When guests contribute to your fund you can request to have the funds transferred directly into your bank account at any time. We make it easy to keep track of who gifted what, as well as the progress of all your funds. </p> <p class="how_it_wks_top_adj_cl">At Nook+Cove we charge the lowest transaction fee available at 2.5%. This fee is paid by the guest and goes directly to the credit card companies. </p> <p class="how_it_wks_top_adj_cl">We don't keep any percentages or make any money from cash funds. We're just happy to be able to provide you this service! </p> </div> </div> </div> </div>
			<div id="s3" class="how_it_wks_mt_adj_cl"> <div class="how_it_wks_pdnt_adj_cl"> <div class="step three"> <img src="resources/images/registry_learnmore/room_funds_img.png"> <div class="black horizontal line mobile"></div> <div class="description"> <h1 class="title"><font class="heading_font_rt_dsp">R</font>OOM <font class="heading_font_rt_dsp">F</font>UNDS</h1> <p>Do you need amazing furniture and decor for your home but just not right away? Our Room Fund feature lets you create a fund for any space that you want to decorate at a later time. </p> <p class="how_it_wks_top_adj_cl">Your room funds will convert into Nook+Cove credit that can be used on the website at anytime. You can use the credit to shop any of our design boards or use them to consult one of our designers for a personalized e-design experience. Our design process is entirely online, customized to your needs and style, flexible with your schedule and most importantly, a lot of fun! </p> <p class="how_it_wks_top_adj_cl">Part of our e-design process includes a customized design board that you will be able to shop from using your funds. Learn more about our design services <a href="lmDesignServices" target="_blank" class="hiw_link_dsplay">here</a>. </p> <p class="how_it_wks_top_adj_cl">At Nook+Cove we specialize in decor and design and it shows! Create a Room Fund today so that you can have the home of your dreams tomorrow! </p> </div> </div> </div> </div>			
			<div class="hrben_bott_height_adj"></div> </div> </div> </div>
		</body>
</html>